dist: trusty
language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install libcurl4-gnutls-dev --yes
  - git clone https://github.com/clibs/clib.git /tmp/clib
  - cd /tmp/clib
  - make
  - sudo make install
  - cd -

install: clib install --dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make test
